import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/components/LoginBtn/LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  
  return (
    <html lang="ko">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">board</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <LoginBtn login={session}></LoginBtn>
        </div>
        {children}
      </body>
    </html>
  );
}

// 회원가입하면 서버를 통해 DB에 저장하고
// 로그인하면 서버를 통해 아이디와 비번이 DB와 일치하는지 비교하고
// 맞으면 입장권 발급
// 서버에 Get/Post요청시 입장권 함께 제출하게 작성
// `쿠키저장소` 이용
// session(ID) 또는 token(JWT) 입장권
// OAuth : 타사이트 정보 이용 (소셜로그인)
// Auth.js, NextAuth.js 라이브러리 제공

// Vercel 배포
// npm install -g vercel
// vercel login
// 프로젝트 디렉토리에서 vercel 입력해서 배포
